spring.application.name=barang-kita
server.port=${PORT:8080}

# Hardcoded exactly to Supabase to bypass hidden local variables
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.ulftxttnadxfgpnzxzbq
spring.datasource.password=${DB_PASSWORD}

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security & Cloudinary
jwt.secret=${JWT_SECRET:404e635266556a586e3272357538782f413f4428472b4b6250645367566b5970}
jwt.expiration=${JWT_EXPIRATION:86400000}
cloudinary.url=${CLOUDINARY_URL:cloudinary://789395211319988:kLgKGNyXgnM5ZmKMWsZxa74Lg1s@dsuvpicqj}

logging.level.com.barangkita.barang_kita.security=INFO